version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    env_file:
      - .env
    ports:
      - '5432:$PG_PORT'
    volumes:
      - ./database/$POSTGRES_DB:/var/lib/postgresql/data/
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$PG_HOST:$PG_PORT/$POSTGRES_DB
      NODE_ENV: development
      PORT: $PORT
    # entrypoint: /bin/sh './scripts/node-dev.sh'
    ports:
      - "3000:$PORT"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules