version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wmp-db
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./database/wmp-db:/var/lib/postgresql/data/